name: Run Selenium Automation Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: 

# إعطاء صلاحيات للسيرفر عشان يقدر يكتب ويرفع الـ Report على GitHub Pages
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Selenium Tests
      run: mvn test -Dheadless=true -Dmaven.test.failure.ignore=true

    # 🚀 خطوة 1: جلب تاريخ التقارير القديمة (عشان يظهر لك الـ Trend في الـ Allure)
    - name: Get Allure history
      <: "gh-pages"
      with:
        target_branch: gh-pages
        build_number: ${{ github.run_number }}
        allure_results: target/allure-results
        allure_history: allure-history
        keep_reports: 20

    # 🚀 خطوة 2: توليد ونشر التقرير على برانش gh-pages
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history